---
# tasks file for elastic_kibana

- name: "Copy elasticsearch deb package"
  ansible.builtin.copy:
    src: "{{ directory_path_for_deb_pack_elastic }}"
    dest: "/tmp/{{ elastic_deb }}"
    mode: 0755

- name: "Copy kibana deb package"
  ansible.builtin.copy:
    src: "{{ directory_path_for_deb_pack_kibana }}"
    dest: "/tmp/{{ kibana_deb }}"
    mode: 0755

- name: Install a .deb package of elasticsearch
  ansible.builtin.apt:
    deb: "/tmp/{{ elastic_deb }}"

- name: Install a .deb package of kibana
  ansible.builtin.apt:
    deb: "/tmp/{{ kibana_deb }}"

- name: "Start systemd service to lunch elasticsearch"
  ansible.builtin.systemd:
    daemon-reload: true
    state: started
    enabled: yes
    name: elasticsearch

- name: "Start systemd service to lunch kibana"
  ansible.builtin.systemd:
    daemon-reload: true
    state: started
    enabled: yes
    name: kibana

- name: "Ensure passwd file for elasticsearch exists"
  ansible.builtin.stat:
    path: "/home/{{ ansible_user }}/secret"
  register: elasticsearch

- name: "Reset elasticsearch passwd"
  ansible.builtin.expect:
    command: /bin/bash -c "/usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic > /home/{{ ansible_user }}/secret"
    responses:
      (.*)Please confirm that you would like to continue \[y/N\](.*): "y"
  when: not elasticsearch.stat.exists

- name: "Chmod for elasticsearch passwd"
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/secret"
    mode: 0600

- name: "Add the user kibana to the group elasticsearch"
  ansible.builtin.user:
    name: kibana
    groups: elasticsearch
    append: true

- name: "Ensure passwd file for kibana exists"
  ansible.builtin.stat:
    path: "/home/{{ ansible_user }}/kibana_secret"
  register: kibana_token_file

- name: "Reset kibana passwd"
  ansible.builtin.expect:
    command: /bin/bash -c "/usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana_system > /home/{{ ansible_user }}/kibana_secret"
    responses:
      (.*)Please confirm that you would like to continue \[y/N\](.*): "y"
  when: not kibana_token_file.stat.exists

- name: "Chmod for kibana passwd"
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/kibana_secret"
    mode: 0600

- name: "Register the kibana passwd"
  ansible.builtin.shell:
    cmd: "cat /home/{{ ansible_user }}/kibana_secret | grep New | cut -c 12-33"
  register: kibana_token

- name: "Set fact for kibana_token variable"
  set_fact: 
    kibana_token={{ kibana_token.stdout }}

- name: "Set kibana config file"
  ansible.builtin.template:
    src: kibana.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: 0660
  notify:
  - Restart systemd unit kibana