---
# tasks file for prometheus

- name: "Ensure prometheus bin exists"
  ansible.builtin.stat:
    path: "/usr/local/bin/prometheus"
  register: prometheus_bin

- name: "Make the group for prometheus"
  ansible.builtin.group:
    name: prometheus
    state: present

- name: "Add the user and group prometheus"
  ansible.builtin.user:
    name: prometheus
    group: prometheus
    shell: /bin/false
    comment: Prometheus server user

- name: "Create a directory for prometheus download"
  ansible.builtin.file:
    path: /tmp/prometheus
    state: directory
    mode: 0755

- name: "Download and extract prometheus version in default folder"
  ansible.builtin.unarchive:
    src: "{{ prometheus_url_ver }}"
    dest: /tmp/prometheus
    remote_src: true
    list_files: yes
    extra_opts: [--strip-components=1]

- name: "Copy prometheus bin file with owner and permissions"
  ansible.builtin.copy:
    src: /tmp/prometheus/prometheus
    dest: /usr/local/bin/prometheus
    mode: 0755
    remote_src: true

- name: "Copy prometool bin file with owner and permissions"
  ansible.builtin.copy:
    src: /tmp/prometheus/promtool
    dest: /usr/local/bin/promtool
    mode: 0755
    remote_src: true

- name: "Create a directory for prometheus config file"
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0750

- name: "Create a directory for prometheus DB"
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0750

- name: "Set prometheus option file"
  ansible.builtin.template:
    src: prometheus_option.j2
    dest: /etc/systemd/prometheus
  notify:
  - Restart systemd unit prometheus

- name: "Set prometheus systemd file"
  ansible.builtin.template:
    src: prometheus_systemd_unit.j2
    dest: /usr/lib/systemd/system/prometheus.service
  notify:
  - Restart systemd unit prometheus

- name: "Set prometheus config file"
  ansible.builtin.template:
    src: prometheus_config.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0640
  notify:
  - Reload systemd unit prometheus

- name: "Start systemd service to lunch prometheus"
  ansible.builtin.systemd:
    daemon-reload: true
    state: started
    enabled: yes
    name: prometheus
  when: not prometheus_bin.stat.exists




